//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoBird.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class MailServerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MailServerSettings defaultInstance = ((MailServerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MailServerSettings())));
        
        public static MailServerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imap.gmail.com")]
        public string INPUT_HOST {
            get {
                return ((string)(this["INPUT_HOST"]));
            }
            set {
                this["INPUT_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("993")]
        public int INPUT_PORT {
            get {
                return ((int)(this["INPUT_PORT"]));
            }
            set {
                this["INPUT_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IMAP")]
        public string INPUT_METHOD {
            get {
                return ((string)(this["INPUT_METHOD"]));
            }
            set {
                this["INPUT_METHOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string OUTPUT_HOST {
            get {
                return ((string)(this["OUTPUT_HOST"]));
            }
            set {
                this["OUTPUT_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int OUTPUT_PORT {
            get {
                return ((int)(this["OUTPUT_PORT"]));
            }
            set {
                this["OUTPUT_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("korotuntest@gmail.com")]
        public string USERNAME {
            get {
                return ((string)(this["USERNAME"]));
            }
            set {
                this["USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USER_PASSWORD {
            get {
                return ((string)(this["USER_PASSWORD"]));
            }
            set {
                this["USER_PASSWORD"] = value;
            }
        }
    }
}
